/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class occ_mobile_example2_OCC */

#ifndef _Included_occ_mobile_example2_OCC
#define _Included_occ_mobile_example2_OCC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     occ_mobile_example2_OCC
 * Method:    result
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_occ_mobile_example2_OCC_result
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
